classes/urls.py
from django.urls import path

from . import views

app_name = "classes"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index_classes"),
    path("<slug:slug>/", views.CourseDetailView.as_view(), name="course_detail"),
    path(
        "<slug:course_slug>/<slug:slug>/",
        views.LessonDetailView.as_view(),
        name="lesson_detail",
    ),
]

flying_circus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("", include("classes.urls")),
]

classes/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField

# Create your models here.
class Course(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=100)
    levels = [
        ("1", "Débutant"),
        ("2", "Intermédiaire"),
        ("3", "Avancé"),
    ]
    level = models.CharField(max_length=1, choices=levels, default="1")
    order = models.IntegerField(default=1)
    content = HTMLField()
    manager = models.OneToOneField(User, on_delete=models.RESTRICT)

    def __str__(self):
        return self.title


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=100)
    order = models.IntegerField(default=1)
    content = HTMLField()
    manager = models.OneToOneField(User, on_delete=models.RESTRICT)

    def __str__(self):
        return self.title

classes/views.py
from typing import List
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Course, Lesson

# Create your views here.


class IndexView(ListView):
    model = Course
    ordering = "order"


class CourseDetailView(DetailView):
    model = Course


class LessonDetailView(DetailView):
    model = Lesson

classes/templates/classes/course_detail.html
{% extends "base.html" %}
{% block title %}{{course.title|title}}{% endblock %}

{% block content %}

<h1>{{ course.title|title }}</h1>
        

        {{ course.content |safe }}

        <p>Par <strong>{{course.manager.first_name}} {{course.manager.last_name}}</strong></p>


{% endblock %}

classes/templates/classes/course_list.html
{% extends "base.html" %}
{% block title %}Cours{% endblock %}
{% block content %}

<h1>Les Cours</h1>
{% if course_list %}
<div class="row gx-5">
        <div class="col-8">
                <div>
                        {% for course in course_list %}
                        <h2><a href="{% url 'classes:course_detail' course.slug %}">{{course.title|title}}</a>
                        </h2>
                        <p class="course-summary">Responsable : <strong>{{course.manager.first_name}} {{course.manager.last_name}}</strong></p>
                        
                        <ol>
                                {% for lesson in course.lesson_set.all %}
                                        <li><a href="{% url 'classes:lesson_detail' course.slug lesson.slug %}">{{ lesson.title }}</a></li>
                                {% endfor %}
                        </ol>
                        <hr>
                        {% endfor %}

                </div>

                <br>
                <div class="pagination">
                        <nav aria-label="Page navigation">
                                <ul class="pagination">
                                        {% if page_obj.has_previous %}
                                        <li class="page-item"><a class="page-link"
                                                        href="?page={{ page_obj.previous_page_number }}">Précédente</a>
                                        </li>
                                        {% endif %}

                                        {% for page in paginator%}
                                        <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">
                                                        {{ forloop.counter }}</a></li>

                                        {% endfor %}

                                        {% if page_obj.has_next %}
                                        <li class="page-item"><a class="page-link"
                                                        href="?page={{ page_obj.next_page_number }}">Suivante</a></li>
                                        {% endif %}
                                </ul>
                        </nav>

                </div>
        </div>

</div>

{% else %}
<p>Aucun course.</p>
{% endif %}
{% endblock %}

classes/templates/classes/lesson_detail.html
{% extends "base.html" %}
{% block title %}{{lesson.title|title}}{% endblock %}

{% block content %}

<h1>{{ lesson.title|title }}</h1>
        

        {{ lesson.content |safe }}

        <p>Par <strong>{{lesson.manager.first_name}} {{lesson.manager.last_name}}</strong></p>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- py-script -->
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script> 

    <!-- boostrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>{% block title %}Flying Circus{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎪</text></svg>">

    {% load static%}

</head>

<body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Python Flying Circus</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link" href="#">TODO 2</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        TODO1
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'classes:index_classes' %}">
                            TODO2</a>


                        <!--<a class="dropdown-item" href="#">Action</a>-->
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <br>

    {% endblock %}
    <div class="container">

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

    <!-- JavaScript -->
    <!-- Jquery and Popper-->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>